from __future__ import annotations

from abc import ABC, abstractmethod

from exca_dance.core.models import JointName

class ExcavatorBridgeInterface(ABC):
    @abstractmethod
    def send_command(self, joint_angles: dict[JointName, float]) -> None: ...
    @abstractmethod
    def get_current_angles(self) -> dict[JointName, float]: ...
    @abstractmethod
    def is_connected(self) -> bool: ...
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...

class VirtualBridge(ExcavatorBridgeInterface):
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
    def send_command(self, joint_angles: dict[JointName, float]) -> None: ...
    def get_current_angles(self) -> dict[JointName, float]: ...
