"""Core game logic for Exca Dance."""

from .models import (
    JointName,
    Judgment,
    JointState,
    ExcavatorState,
    BeatEvent,
    BeatMap,
    HitResult,
    LeaderboardEntry,
    KeyBinding,
)
from .constants import (
    JOINT_LIMITS,
    JUDGMENT_WINDOWS,
    SCORE_VALUES,
    COMBO_THRESHOLDS,
    TARGET_FPS,
    SCREEN_WIDTH,
    SCREEN_HEIGHT,
    JOINT_ANGULAR_VELOCITY,
    DEFAULT_KEY_BINDINGS,
    BOOM_LENGTH,
    ARM_LENGTH,
    BUCKET_LENGTH,
    DEFAULT_JOINT_ANGLES,
    GAMEPAD_AXIS_DEADZONE,
    GAMEPAD_AXIS_MAP,
    GAMEPAD_BUTTON_A,
    GAMEPAD_BUTTON_B,
    GAMEPAD_BUTTON_START,
)

__all__ = [
    "JointName",
    "Judgment",
    "JointState",
    "ExcavatorState",
    "BeatEvent",
    "BeatMap",
    "HitResult",
    "LeaderboardEntry",
    "KeyBinding",
    "JOINT_LIMITS",
    "JUDGMENT_WINDOWS",
    "SCORE_VALUES",
    "COMBO_THRESHOLDS",
    "TARGET_FPS",
    "SCREEN_WIDTH",
    "SCREEN_HEIGHT",
    "JOINT_ANGULAR_VELOCITY",
    "DEFAULT_KEY_BINDINGS",
    "BOOM_LENGTH",
    "ARM_LENGTH",
    "BUCKET_LENGTH",
    "DEFAULT_JOINT_ANGLES",
    "GAMEPAD_AXIS_DEADZONE",
    "GAMEPAD_AXIS_MAP",
    "GAMEPAD_BUTTON_A",
    "GAMEPAD_BUTTON_B",
    "GAMEPAD_BUTTON_START",
]
