from exca_dance.core.models import JointName

class KeyBindingManager:
    def __init__(self, filepath: str = ...) -> None: ...
    def get_binding(self, joint: JointName) -> tuple[int, int]: ...
    def set_binding(self, joint: JointName, positive_key: int, negative_key: int) -> None: ...
    def get_joint_for_key(self, key: int) -> tuple[JointName, int] | None: ...
    def save(self) -> None: ...
    def load(self) -> None: ...
    def reset_to_defaults(self) -> None: ...
